### ISSUE TITLE
Two of the demo samples don't work

### ISSUE THREAD

**Issue by mthome** [drewharvey/VaadinAudioPlayer#6]
Selecting mpeg-laery-3-8k.wav results in:
Feb 05, 2018 2:46:24 PM com.vaadin.addon.audio.shared.util.Log logMessage
SEVERE: [DemoUI] File read failed
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input stream
	at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1121)
	at com.vaadin.addon.audio.demo.DemoUI.decodeToPcm(DemoUI.java:604)
	at com.vaadin.addon.audio.demo.DemoUI.access$400(DemoUI.java:55)
	at com.vaadin.addon.audio.demo.DemoUI$1.onSelected(DemoUI.java:562)
	at com.vaadin.addon.audio.demo.DemoUI$FileSelector$1.buttonClick(DemoUI.java:505)
...
Feb 05, 2018 2:46:24 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.NullPointerException
	at com.vaadin.addon.audio.server.util.Endian.readLE(Endian.java:27)
	at com.vaadin.addon.audio.server.util.WaveUtil.getFmtChunkSize(WaveUtil.java:53)
	at com.vaadin.addon.audio.server.util.WaveUtil.getDataChunkStart(WaveUtil.java:58)
	at com.vaadin.addon.audio.server.util.WaveUtil.getDataStartOffset(WaveUtil.java:84)
	at com.vaadin.addon.audio.demo.DemoUI.createWaveStream(DemoUI.java:624)
....

Selecting AndresssonVietnamWarProtests.wav results in the different behavior:
INFO: [com.vaadin.addon.audio.demo.DemoUI$FileSelector$1@1145a1f4] add stream AddressonVietnamWarProtests.wav
Feb 05, 2018 2:48:33 PM com.vaadin.addon.audio.shared.util.Log logMessage
INFO: [AudioPlayer] received request for chunk 0
Feb 05, 2018 2:48:33 PM com.vaadin.addon.audio.shared.util.Log logMessage
INFO: [WaveEncoder] writing samples from offset 0 to 241956
Feb 05, 2018 2:48:33 PM com.vaadin.addon.audio.shared.util.Log logMessage
INFO: [WaveEncoder] data length is 483912
Feb 05, 2018 2:48:33 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.nio.BufferUnderflowException
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
	at com.vaadin.addon.audio.server.encoders.WaveEncoder.encode(WaveEncoder.java:48)
	at com.vaadin.addon.audio.server.Stream$1.run(Stream.java:247)
	at java.lang.Thread.run(Thread.java:748)
	at com.vaadin.addon.audio.server.Stream.serviceChunkRequests(Stream.java:268)
	at com.vaadin.addon.audio.server.Stream.getChunkData(Stream.java:225)
	at com.vaadin.addon.audio.server.AudioPlayer$1.requestChunk(AudioPlayer.java:60)
...

**Comment by TatuLund** [comment]
mpeg-laery-3-8k.wa: AudioSystem does not support MPEG encoded WAVs https://stackoverflow.com/questions/29713371/javas-sound-api-doesnt-work-with-all-wav-files

AndresssonVietnamWarProtests.wav: Fix is here https://github.com/drewharvey/VaadinAudioPlayer/pull/14/commits/a53d451d4175bca9cf67e2a10794e1090e5f1773 However the file decodes as silent, it seems to be issue in AudioSystem
